const styles: Record<string, Record<string, string | number>> = {
  body: {
    fontFamily: '"Anek Gujarati", sans-serif !important',
  },
  startPageContainer: {
    display: 'flex',
    minHeight: '100vh',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    position: 'relative',
  },
  startPageHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    padding: '1rem',
    color: 'white',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  leftStartPageHeader: {
    display: 'flex',
    alignItems: 'center',
  },
  startPageTitleHeader: {
    fontSize: '48px',
    fontWeight: 'medium',
    color: 'black',
    marginLeft: '30px',
    fontFamily: '"Anek Gujarati", sans-serif',
  },
  rightStartPageHeader: {
    display: 'flex',
    alignItems: 'center',
    fontFamily: '"Anek Gujarati", sans-serif !important',
    width: '30%',
    justifyContent: 'space-between',
    fontSize: '24px',
    color: 'black',
  },
  startPageIntro: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    fontFamily: '"Anek Gujarati", sans-serif !important',
    justifyContent: 'space-between',
  },
  startPageWelcome: {
    fontSize: '80px',
    fontWeight: 'medium',
  },
  startPageRising: {
    fontSize: '36px',
    fontWeight: 'light',
    width: '416px',
    alignItems: 'center',
    alignSelf: 'center',
    textAlign: 'center',
    marginTop: '40px',
    marginBottom: '40px',
  },
  startPageButton: {
    fontSize: '20px',
    fontWeight: 'medium',
    width: '236px',
    height: '63px',
    backgroundColor: '#f57f61',
    borderRadius: '40px',
    color: 'white',
  },
};

export default styles;
